title: Gerard L. Donahue
url: "https://gerard.github.io"

markdown: kramdown

tracking_id: #


sass:
    style: compressed
    sass_dir: _sass

# nav:
#  - name: "Resume"
#    link: "resume.pdf"
#  - name: "Contact"
#    link: "contact"