# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gerard Donahue, Doctoral Researcher
email: donahuegerard@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gerard Donahue is a doctoral student of computer science at Northeastern University
  working at the intersection of reinforcement learning and computer vision.  
baseurl: "/home/" # the subpath of your site, e.g. /blog
url: "https://donahuegerard.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  gerardDonahue

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

footer: yes
footer_url: "https://github.com/gerardDonahue"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
