title: Gerard Donahue, Doctoral Researcher
email: donahuegerard@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gerard Donahue is a doctoral student of computer science at Northeastern University
  working at the intersection of reinforcement learning and computer vision.  
baseurl: "/researcher/" # the subpath of your site, e.g. /blog
url: "https://donahuegerard.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  gerardDonahue

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
